#!/bin/bash

set -eu
set -o pipefail

SDPATH="$(dirname "${BASH_SOURCE[0]}")"
if [ ! -d "${SDPATH}" ]; then SDPATH="${PWD}"; fi
readonly SDPATH="$(cd -P "${SDPATH}" && pwd)"

PRJ_ROOT_PATH="${SDPATH}/.."
readonly PRJ_ROOT_PATH="$(cd "${PRJ_ROOT_PATH}" && pwd)"

cd "${PRJ_ROOT_PATH}" && echo cd "${PWD}"

CMD=(rm -vrf node_modules)
echo + "${CMD[@]}" && "${CMD[@]}"

CMD=(rm -vrf packages/*/node_modules)
echo + "${CMD[@]}" && "${CMD[@]}"

CMD=(rm -vrf packages/*/dist)
echo + "${CMD[@]}" && "${CMD[@]}"
